openapi: "3.0"
info:
  title: Get Content
  description: This is a sample for getting just a lot of content. maybe a PRPL pattern, lets see how much we can enforce it from here.
  termsOfService: http://example.com/terms/
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.1
servers: []
paths:
  /:
  get:
    descriptions:
      '200':
        description:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/'

components:
  schemas:
    ErrorModel:
      type: object
      required:
      - message
      - code
      properties:
        message:
          type: string
        code:
          type: integer
          minimum: 100
          maximum: 600
    ExtendedErrorModel:
      allOf:
      - $ref: '#/components/schemas/ErrorModel'
      - type: object
        required:
        - rootCause
        properties:
          rootCause:
            type: string
security:
tags:
externalDocs: